CREATE TABLE moto (
    id BIGSERIAL PRIMARY KEY,
    modelo VARCHAR(255) NOT NULL,
    placa VARCHAR(10) NOT NULL UNIQUE,
    zona VARCHAR(50),
    multa BOOLEAN DEFAULT FALSE,
    falha_mecanica BOOLEAN DEFAULT FALSE,
    roubada BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);